stages:
  - terraform_plan
  - terraform_apply
  - ansible_configure

variables:
  TF_IN_AUTOMATION: "true"
  ANSIBLE_HOST_KEY_CHECKING: "False"

before_script:
  - echo "Starting CI/CD flow..."

terraform_plan:
  stage: terraform_plan
  script:
    - cd terraform
    - terraform init -input=false
    - terraform plan -out=tfplan.out
  artifacts:
    paths:
      - terraform/tfplan.out

terraform_apply:
  stage: terraform_apply
  script:
    - cd terraform
    - terraform apply -auto-approve tfplan.out

ansible_configure:
  stage: ansible_configure
  script:
    - cd ansible
    - ansible-playbook -i aws_ec2_inventory.py prometheus_grafana.yml
